### ISSUE TITLE
null: false with a default defined should not create a presence validation

### ISSUE THREAD

**Issue by hampei** [SchemaPlus/schema_validations#18]
I always make all my columns that have a default 'not null' since I like the certainty of things never being null.

**Comment by ronen** [comment]
@hampei yes, good point.

That would technically be a backwards-incompatibiliy so would need a version bump.  FYI If I were doing a version bump, I'd be awfully tempted to take the opportunity to update the internals to use schema_plus 2.0 mechanism for extending ActiveRecord (but then it would only work for ActiveRecord >= 4.2 and Ruby >= 2.1).

In the meantime you can disable the validation for the column in question using

```ruby
class MyModel < ActiveRecord::Base
  schema_validations except: :my_column_name
end
```

Thanks for pointing this out

**Comment by boazy** [comment]
Pull request #50 should solve it with a mostly backward-compatible configuration option.

**Comment by boazy** [comment]
Issue is solved, but we're now considering it a bug, so the configuration option is removed. You can just upgrade to the latest version and you'll no longer have presence validation when an empty default value is defined (there will still be presence validation when using non-empty default values).
