### ISSUE TITLE
'validates_presence' is too strict for child of `belongs_to`

### ISSUE THREAD

**Issue by RichardBradley** [SchemaPlus/schema_validations#2]
If I have a parent - child model:

    class Parent
    end
    
    class Child
       belongs_to :parent
    end

and I define it with a "not null" parent_id column in the database, then schema_validations will add a "validates_presence_of" for my "parent" property on Child.

This seems fine, but it breaks code like this, which previously worked:

    parent = Parent.new
    parent.child = child.new
    parent.save!

I suppose I have to assign both directions of the association now.

**Comment by ronen** [comment]
Closing this as (very) stale

**Comment by donv** [comment]
This is still an issue, I think.  From your reproduction, change "has_one" to "has_many" and add your unsaved Child to "parent.children".

**Comment by donv** [comment]
This is not specific to schema_validations.  Any presence_of validation on a belongs_to id will fail.  The problem is that schema_validations adds it automatically.

Adding a validation for the presence of the associated object instead of the id could be an alternative.

http://blog.launchacademy.com/validating-associations-in-rails/

**Comment by donv** [comment]
I think a good validation for a NOT NULL column for a has_many<=>belongs_to foreign key would be

```ruby
validates :parent_id, presence: true, unless: -> { new_record? && parent.try(:new_record?) }
```

@ronen What do you think?

**Comment by ronen** [comment]
@donv I'm still not recreating an error.  Here's what I have:

```ruby
 context "with belongs_to and has_many" do
    before(:each) do
      ActiveRecord::Schema.define do
        create_table :parents, :force => true do |t|
          t.string :name
        end

        create_table :children, :force => true do |t|
          t.integer :parent_id, :null => false
          t.string :name
        end
      end

      with_auto_validations do
        class Parent < ActiveRecord::Base
          has_many :children, :dependent => :destroy
        end

        class Child < ActiveRecord::Base
          belongs_to :parent
        end
      end
    end

    it "should not break association assignment" do
      child = Child.new
      expect(child.error_on(:parent).size).to eq(1)  # confirm validates_presence_of

      parent = Parent.new
      parent.children << child
      expect { parent.save! }.to_not raise_error
      expect { child.save! }.to_not raise_error
    end
  end
```
I've commit this into a branch validates-presence-belongs-to.   Do you want to see if you can get it to fail?

**Comment by donv** [comment]
Will do!
