### ISSUE TITLE
Validate decimal range

### ISSUE THREAD

**Issue by felixbuenemann** [SchemaPlus/schema_validations#35]
It would be great if schema_validations could add a validation for decimal / numeric range. These fields are defined with a precision (total number of digits) and scale (number of fractional digits).

So the range for a decimal column with precision 4 and scale 2 is ±99.99 or < 10^2 and > -10^2 using the formula abs(10^(precision - scale)).

This can be expressed as an ActiveRecord validation:

```ruby
validates :foo, numericality: { less_than: 10**2, greater_than: -10**2 } 
```

Here's the error you get on postgres, when the value overflows:

```sql
SELECT 100.99::numeric(4,2);
ERROR:  numeric field overflow
DETAIL:  A field with precision 4, scale 2 must round to an absolute value less than 10^2.
```

**Comment by felixbuenemann** [comment]
This seems to be roughly 4 lines of code to implement, so I'll give it a try.

**Comment by ronen** [comment]
@felixbuenemann sounds good, i'm happy to accept a PR if you get it working

**Comment by felixbuenemann** [comment]
Yes, I'm currently down with a bad flu, that's why I didn't get around to it. Will look into it when I'm better.
