### ISSUE TITLE
Rails 5 support

### ISSUE THREAD

**Issue by maisumakun** [SchemaPlus/schema_validations#42]
Currently, this gem is locked to ActiveRecord 4.2.x. Will this support Rails 5 ?

**Comment by ronen** [comment]
Yes, we are in the process of upgrading all SchemaPlus gems to Rails 5.  

(By "we" I really mean @boazy who's doing all the hard work :)

**Comment by plicjo** [comment]
I've got a PR up with schema_validations running on Rails 5 and Postgres. https://github.com/SchemaPlus/schema_validations/pull/44

That should help!

**Comment by boazy** [comment]
@ronen
Can you release a new version of the gem?
Perhaps we should make releases easier by just letting Travis CI do that on tags.
