### ISSUE TITLE
Rails 5.1 support

### ISSUE THREAD

**Issue by zharikovpro** [SchemaPlus/schema_validations#52]
It worked fine so far with Rails 5.0. With 5.1 bundler shows error:

> Bundler could not find compatible versions for gem "activerecord"
> rails (= 5.1.0) was resolved to 5.1.0, which depends on activerecord (= 5.1.0)
> schema_validations (~> 2.2.x) was resolved to 2.2.1, which depends on activerecord (< 5.1, >= 4.2.1)

Do you need some help with testing to support Rails 5.1? Probably not very much changed since 5.0, and this simple change in gemspec may just work:

`s.add_dependency("activerecord", ">= 4.2.1", "<= 5.1")`

**Comment by boazy** [comment]
Thanks @zharikovpro
I don't have much time working on that myself right now, but if you can run all the unit tests fine after the change, just submit a PR with this one line changed and I will release it.

**Comment by zharikovpro** [comment]
@boazy thanks, will try

**Comment by zharikovpro** [comment]
Turned out it depends on schema_plus_columns, made PR too: https://github.com/SchemaPlus/schema_plus_columns/pull/7

**Comment by zharikovpro** [comment]
Also, would you consider `gem.add_dependency "activerecord", "~> 5.0"` as in schema_plus_core, which works just fine?

**Comment by ronen** [comment]
Thanks to @iagopiimenta, schema_plus_core has been updated. Then it was a quick matter for me to update this gem. Version 2.3.0 is released now.
