### ISSUE TITLE
Rails 5.2

### ISSUE THREAD

**Issue by frostpuppet** [SchemaPlus/schema_validations#59]
Unable to use with Rails 5.2 and AR 5.2

**Comment by frostpuppet** [comment]
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies....
Bundler could not find compatible versions for gem "activerecord":
  In Gemfile:
    rails (~> 5.2.1) was resolved to 5.2.1, which depends on
      activerecord (= 5.2.1)

    schema_validations (~> 2.3.0) was resolved to 2.3.0, which depends on
      schema_plus_columns was resolved to 0.1.2, which depends on
        activerecord (~> 4.2)

**Comment by urkle** [comment]
This is now usable on Rails 5.2 (all dependencies have been updated to support Rails 5.2)
