### ISSUE TITLE
Add support for Rails 6

### ISSUE THREAD

**Issue by vassyz** [SchemaPlus/schema_validations#62]
Rails 6 is currently not supported. The Ruby version also has to be bumped to 2.5.

**Comment by atomical** [comment]
Is there a lot of work to be done to accomplish this? This is blocking our upgrade.

**Comment by ronen** [comment]
We really need somebody to volunteer to take over SchemaPlus development & maintenance, or it will unfortunately slip into abandonware.   Maybe it already has :(   All the (former) principal developers are, for various reasons, not currently in a position to maintain it.

Anyone who wants to step up will be warmly welcomed!

**Comment by atomical** [comment]
```ruby
# Rails 6 
NoMethodError:
  undefined method `alias_method_chain' for #<Class:ActiveRecord::Base>
  Did you mean?  alias_method
```

I'll try to fork it and see what I can do.

**Comment by ronen** [comment]
> I'll try to fork it and see what I can do.

Great, good luck!   Feel free to contact me if you have any questions (I may or may not be able to help...)

**Comment by buermann** [comment]
Is there a new library that performs this work for Rails 6 that I just haven't heard about, or is this terrific project still dead in the water with nothing to replace it?

**Comment by ronen** [comment]
Sadly, this project seems to be dead in the water until/unless somebody steps up to maintain it 😞

**Comment by urkle** [comment]
@vassyz @atomical @buermann work is being done now to add rails 6 support (and follow-on for rails 7)  Expect new releases within the next few weeks.

We have already updated schema_dev, and modware, and schema_monkey.   the core is next followed by the final gems like this one.

**Comment by atomical** [comment]
Great news!
