### ISSUE TITLE
Is it possible to cancel validation?

### ISSUE THREAD

**Issue by thehappycoder** [SchemaPlus/schema_validations#7]
We use schema_validations 0.2.2 and rails2. One validation on not null column isn't really needed because we want to save empty strings.

Now we get: ActiveRecord::RecordInvalid: Validation failed: Pins can't be blank

Pins is the varchar column.

**Comment by ronen** [comment]
Oops, never replied to this, years ago!  Sigh.  FWIW the README does explain how to do this, albeit not very clearly.
